/**
 * AI market reports — Pro only.
 *
 * Educational information, labelled as such in the prompt, in the stored row,
 * and on screen. A generated paragraph about markets is exactly the kind of
 * content a reader can mistake for a recommendation, so the disclaimer travels
 * with the report rather than living in a footer somewhere.
 */

import { useState } from 'react';
import { PageHeader } from '@/components/PageHeader';
import {
  Badge,
  Button,
  Callout,
  ConfirmButton,
  EmptyState,
  ErrorMessage,
  LoadingState,
  Panel,
} from '@/components/ui';
import { ProGate } from '@/components/ProGate';
import { useAuth } from '@/features/auth/AuthContext';
import { useCollection } from '@/hooks/useCollection';
import { deleteRow } from '@/services/crud';
import { apiRequest, ApiClientError } from '@/lib/api/client';
import type { MarketReportRow } from '@/types/database';
import { fmtRelativeTime } from '@/lib/format';
import './market-reports.css';

export function MarketReportsPage() {
  const { user } = useAuth();
  const { items: reports, loading, refresh } = useCollection<MarketReportRow>('market_reports', {
    orderBy: 'generated_at',
    ascending: false,
  });
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [viewingId, setViewingId] = useState<string | null>(null);

  const viewing = reports.find((report) => report.id === viewingId) ?? reports[0] ?? null;

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      await apiRequest('/api/ai/market-report');
      await refresh();
    } catch (caught) {
      setError(
        caught instanceof ApiClientError ? caught.message : 'Could not generate a report right now.',
      );
    } finally {
      setGenerating(false);
    }
  }

  if (loading) return <LoadingState label="Loading your reports…" />;

  return (
    <>
      <PageHeader
        title="Market reports"
        feature="ai_market_reports"
        description="A plain-language summary of what markets did recently. Educational background, not a recommendation to do anything."
      />

      <ErrorMessage>{error}</ErrorMessage>

      <ProGate
        feature="ai_market_reports"
        preview={
          <Panel title="Today's market report">
            <p>The major indices closed mixed as investors weighed…</p>
            <p>Mortgage rates eased slightly week over week…</p>
          </Panel>
        }
      >
        <Panel
          title="Generate a report"
          actions={
            <Button variant="primary" loading={generating} onClick={() => void generate()}>
              {generating ? 'Searching…' : 'Generate a new report'}
            </Button>
          }
        >
          <Callout tone="warning" icon="!">
            <strong>This is educational information, not investment advice.</strong> Reports are
            generated by an AI model from web searches. They can be wrong, out of date, or
            incomplete, and they are never a recommendation to buy or sell anything. Check anything
            that matters against a primary source.
          </Callout>

          {reports.length > 1 && (
            <div className="ns-reports__list">
              {reports.slice(0, 10).map((report) => (
                <button
                  key={report.id}
                  type="button"
                  className={`ns-reports__item ${report.id === viewing?.id ? 'ns-reports__item--active' : ''}`}
                  onClick={() => setViewingId(report.id)}
                >
                  {fmtRelativeTime(report.generated_at)}
                </button>
              ))}
            </div>
          )}
        </Panel>

        {!viewing ? (
          <Panel>
            <EmptyState
              title="No reports yet"
              icon="◈"
              action={
                <Button variant="primary" loading={generating} onClick={() => void generate()}>
                  Generate your first report
                </Button>
              }
            >
              NetShift searches the web and summarises the last session across stocks, housing, and
              commodities.
            </EmptyState>
          </Panel>
        ) : (
          <Panel
            title={viewing.as_of ? `Markets — ${viewing.as_of}` : 'Market report'}
            description={`Generated ${fmtRelativeTime(viewing.generated_at)}`}
            actions={
              <ConfirmButton
                variant="link"
                onConfirm={async () => {
                  if (!user) return;
                  await deleteRow('market_reports', viewing.id, user.id);
                  setViewingId(null);
                  await refresh();
                }}
              >
                Delete
              </ConfirmButton>
            }
          >
            {viewing.stock_market && (
              <section className="ns-reports__section">
                <h4>Stocks</h4>
                <p>{viewing.stock_market}</p>
              </section>
            )}

            {viewing.stocks_to_watch?.length > 0 && (
              <section className="ns-reports__section">
                <h4>In the news</h4>
                <ul className="ns-reports__watch">
                  {viewing.stocks_to_watch.map((entry) => (
                    <li key={entry.ticker}>
                      <Badge tone="blue">{entry.ticker}</Badge> {entry.note}
                    </li>
                  ))}
                </ul>
                <p className="ns-reports__caveat">
                  These are companies that were in the news, not suggestions to buy or sell them.
                </p>
              </section>
            )}

            {viewing.housing_market && (
              <section className="ns-reports__section">
                <h4>Housing</h4>
                <p>{viewing.housing_market}</p>
              </section>
            )}

            {viewing.commodities && (
              <section className="ns-reports__section">
                <h4>Commodities</h4>
                <p>{viewing.commodities}</p>
              </section>
            )}

            <Callout tone="neutral">{viewing.disclaimer}</Callout>
          </Panel>
        )}
      </ProGate>
    </>
  );
}
